name: release_to_npm
on:
  release:
    types:
     - published

jobs:

  release_to_npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: actions/setup-node@v4
        with:
          node-version: '22.20.0'
          registry-url: https://registry.npmjs.org/

      - run: |
          npm install -g npm@latest
          npm i
          npm run build
          npm publish